import React from "react";
import { useParams } from "react-router-dom";
import "./City.css";



export default function Ciudad({onFilter, lang}) {
    var params = useParams()
    //console.log(params, 'DEBUGG');
    var city = onFilter(params.ciudadId)
    //console.log(city, 'debug');
    let clima = ""
    let pais = ""
    console.log("AA", lang)

    
       
    

    if (lang === 1) {
        if (city) {

            if (city.weather === "Clouds") clima = "Nublado"
            if (city.weather === "Clear") clima = "Despejado"
            if (city.weather === "Rain") clima = "Lluvioso"
            if (city.weather === "Mist") clima = "Neblina"
            if (city.weather === "Fog") clima = "Niebla" 

            if (city.country === "AF") pais = "(AFGANISTAN)"
            if (city.country === "AX") pais = "(ISLAS ALAND)"
            if (city.country === "AL") pais = "(ALBANIA)"
            if (city.country === "DZ") pais = "(ALGERIA)"
            if (city.country === "AS") pais = "(SAMOA AMERICANA)"
            if (city.country === "AD") pais = "(ANDORRA)"
            if (city.country === "AO") pais = "(ANGOLA)"
            if (city.country === "AI") pais = "(ANGUILA)"
            if (city.country === "AQ") pais = "(ANTARTIDA)"
            if (city.country === "AG") pais = "(ANTIGUA Y BARBUDA)"
            if (city.country === "AR") pais = "(ARGENTINA)"
            if (city.country === "AM") pais = "(ARMENIA)"
            if (city.country === "AW") pais = "(ARUBA)"
            if (city.country === "AU") pais = "(AUSTRALIA)"
            if (city.country === "AT") pais = "(AUSTRIA)"
            if (city.country === "AZ") pais = "(AZERBAIYÁN)"
            if (city.country === "BS") pais = "(BAHAMAS)"
            if (city.country === "BH") pais = "(BAREIN)"
            if (city.country === "BD") pais = "(BANGLADES)"
            if (city.country === "BB") pais = "(BARBADOS)"
            if (city.country === "BY") pais = "(BIELORRUSIA)"
            if (city.country === "BE") pais = "(BELGICA)"
            if (city.country === "BZ") pais = "(BELICE)"
            if (city.country === "BJ") pais = "(BENIN)"
            if (city.country === "BM") pais = "(BERMUDA)"
            if (city.country === "BT") pais = "(BUTAN)"
            if (city.country === "BO") pais = "(BOLIVIA)"
            if (city.country === "BQ") pais = "(CARIBE NEERLANDÉS)"
            if (city.country === "BA") pais = "(BOSNIA AND HERZEGOVINA)"
            if (city.country === "BW") pais = "(BOTSUANA)"
            if (city.country === "BV") pais = "(ISLA BOUVET)"
            if (city.country === "BR") pais = "(BRASIL)"
            if (city.country === "IO") pais = "(TERRITORIO BRITÁNICO DEL OCÉANO ÍNDICO)"
            if (city.country === "BN") pais = "(BRUNEI)"
            if (city.country === "BG") pais = "(BULGARIA)"
            if (city.country === "BF") pais = "(BURKINA FASO)"
            if (city.country === "BI") pais = "(BURUNDI)"
            if (city.country === "KH") pais = "(CAMBODIA)"
            if (city.country === "CM") pais = "(CAMERUN)"
            if (city.country === "CA") pais = "(CANADA)"
            if (city.country === "CV") pais = "(CABO VERDE)"
            if (city.country === "KY") pais = "(ISLAS CAIMAN)"
            if (city.country === "CF") pais = "(REPÚBLICA CENTROAFRICANA)"
            if (city.country === "TD") pais = "(CHAD)"
            if (city.country === "CL") pais = "(CHILE)"
            if (city.country === "CN") pais = "(CHINA)"
            if (city.country === "CX") pais = "(ISLA DE NAVIDAD)"
            if (city.country === "CC") pais = "(ISLAS COCOS)"
            if (city.country === "CO") pais = "(COLOMBIA)"
            if (city.country === "KM") pais = "(COMOROS)"
            if (city.country === "CD") pais = "(REPÚBLICA DEMOCRÁTICA DEL CONGO)"
            if (city.country === "CG") pais = "(CONGO)"
            if (city.country === "CK") pais = "(COOK ISLANDS)"
            if (city.country === "CR") pais = "(COSTA RICA)"
            if (city.country === "CI") pais = "(COSTA DE MARFIL)"
            if (city.country === "HR") pais = "(CROACIA)"
            if (city.country === "CU") pais = "(CUBA)"
            if (city.country === "CW") pais = "(CURAZAO)"
            if (city.country === "CY") pais = "(CHIPRE)"
            if (city.country === "CZ") pais = "(RECUPLICA CHECA)"
            if (city.country === "DK") pais = "(DINAMARCA)"
            if (city.country === "DJ") pais = "(YIBUTI)"
            if (city.country === "DM") pais = "(DOMINICA)"
            if (city.country === "DO") pais = "(RECUPLICA DOMINICANA)"
            if (city.country === "EC") pais = "(ECUADOR)"
            if (city.country === "EG") pais = "(EGIPTO)"
            if (city.country === "SV") pais = "(EL SALVADOR)"
            if (city.country === "GQ") pais = "(GUINEA ECUATORIAL)"
            if (city.country === "ER") pais = "(ERITREA)"
            if (city.country === "EE") pais = "(ESTONIA)"
            if (city.country === "ET") pais = "(ETIOPIA)"
            if (city.country === "FK") pais = "(ISLAS MALVINAS)"
            if (city.country === "FO") pais = "(ISLAS FEROE)"
            if (city.country === "FJ") pais = "(FIJI)"
            if (city.country === "FI") pais = "(FINLANDIA)"
            if (city.country === "FR") pais = "(FRANCIA)"
            if (city.country === "GF") pais = "(GUAYANA FRANCESA)"
            if (city.country === "PF") pais = "(POLINESIA FRANCESA)"
            if (city.country === "TF") pais = "(TIERRAS AUSTRALES Y ANTÁRTICAS FRANCESAS)"
            if (city.country === "GA") pais = "(GABON)"
            if (city.country === "GM") pais = "(GAMBIA)"
            if (city.country === "GE") pais = "(GEORGIA)"
            if (city.country === "DE") pais = "(ALEMANIA)"
            if (city.country === "GH") pais = "(GHANA)"
            if (city.country === "GI") pais = "(GIBRALTAR)"
            if (city.country === "GR") pais = "(GRECIA)"
            if (city.country === "GL") pais = "(GROENLANDIA)"
            if (city.country === "GD") pais = "(GRANADA)"
            if (city.country === "GP") pais = "(GUADELUPE)"
            if (city.country === "GU") pais = "(GUAM)"
            if (city.country === "GT") pais = "(GUATEMALA)"
            if (city.country === "GG") pais = "(GUERNSEY)"
            if (city.country === "GW") pais = "(GUINEA-BISAU)"
            if (city.country === "GN") pais = "(GUINEA)"
            if (city.country === "GY") pais = "(GUYANA)"
            if (city.country === "HT") pais = "(HAITI)"
            if (city.country === "HM") pais = "(ISLAS HEARD Y MCDONALD)"
            if (city.country === "VA") pais = "(CIUDAD DEL VATICANO)"
            if (city.country === "HN") pais = "(HONDURAS)"
            if (city.country === "HK") pais = "(HONG KONG)"
            if (city.country === "HU") pais = "(HUNGRIA)"
            if (city.country === "IS") pais = "(ISLANDIA)"
            if (city.country === "IN") pais = "(INDIA)"
            if (city.country === "ID") pais = "(INDONESIA)"
            if (city.country === "IR") pais = "(IRAN)"
            if (city.country === "IQ") pais = "(IRAQ)"
            if (city.country === "IE") pais = "(IRLANDA)"
            if (city.country === "IM") pais = "(ISLA DE MAN)"
            if (city.country === "IL") pais = "(ISRAEL)"
            if (city.country === "IT") pais = "(ITALIA)"
            if (city.country === "JM") pais = "(JAMAICA)"
            if (city.country === "JP") pais = "(JAPON)"
            if (city.country === "JE") pais = "(JERSEY)"
            if (city.country === "JO") pais = "(JORDAN)"
            if (city.country === "KZ") pais = "(KAZAJISTÁN)"
            if (city.country === "KE") pais = "(KENIA)"
            if (city.country === "KI") pais = "(KIRIBATI)"
            if (city.country === "KP") pais = "(REPÚBLICA POPULAR DEMOCRÁTICA DE COREA)"
            if (city.country === "KR") pais = "(REPÚBLICA DE COREA (COREA DEL SUR))"
            if (city.country === "KW") pais = "(KUWAIT)"
            if (city.country === "KG") pais = "(KIRGUISTÁN)"
            if (city.country === "LA") pais = "(LAOS)"
            if (city.country === "LV") pais = "(LETONIA)"
            if (city.country === "LB") pais = "(LIBANO)"
            if (city.country === "LS") pais = "(LESOTHO)"
            if (city.country === "LR") pais = "(LIBERIA)"
            if (city.country === "LY") pais = "(LIBIA)"
            if (city.country === "LI") pais = "(LIECHTENSTEIN)"
            if (city.country === "LT") pais = "(LITUANIA)"
            if (city.country === "LU") pais = "(LUXEMBURGO)"
            if (city.country === "MO") pais = "(MACAO)"
            if (city.country === "MK") pais = "(MACEDONIA DEL NORTE)"
            if (city.country === "MG") pais = "(MADAGASCAR)"
            if (city.country === "MW") pais = "(MALAWI)"
            if (city.country === "MY") pais = "(MALASIA)"
            if (city.country === "MV") pais = "(MALDIVAS)"
            if (city.country === "ML") pais = "(MALI)"
            if (city.country === "MT") pais = "(MALTA)"
            if (city.country === "MH") pais = "(ISLAS MARSHALL)"
            if (city.country === "MQ") pais = "(MARTINICA)"
            if (city.country === "MR") pais = "(MAURITANIA)"
            if (city.country === "MU") pais = "(MAURICIO)"
            if (city.country === "YT") pais = "(MAYOTTE)"
            if (city.country === "MX") pais = "(MEXICO)"
            if (city.country === "FM") pais = "(ESTADOS FEDERADOS DE MICRONESIA)"
            if (city.country === "MD") pais = "(MOLDOVA)"
            if (city.country === "MC") pais = "(MONACO)"
            if (city.country === "MN") pais = "(MONGOLIA)"
            if (city.country === "ME") pais = "(MONTENEGRO)"
            if (city.country === "MS") pais = "(MONTSERRAT)"
            if (city.country === "MA") pais = "(MARRUECOS)"
            if (city.country === "MZ") pais = "(MOZAMBIQUE)"
            if (city.country === "MM") pais = "(MYANMAR)"
            if (city.country === "NA") pais = "(NAMIBIA)"
            if (city.country === "NR") pais = "(NAURU)"
            if (city.country === "NP") pais = "(NEPAL)"
            if (city.country === "NL") pais = "(PAISES BAJOS)"
            if (city.country === "NC") pais = "(NUEVA CALEDONIA)"
            if (city.country === "NZ") pais = "(NUEVA ZELANDA)"
            if (city.country === "NI") pais = "(NICARAGUA)"
            if (city.country === "NG") pais = "(NIGERIA)"
            if (city.country === "NE") pais = "(NIGER)"
            if (city.country === "NU") pais = "(NIUE)"
            if (city.country === "NF") pais = "(ISLA NORFOLK)"
            if (city.country === "MP") pais = "(ISLAS MARIANAS DEL NORTE)"
            if (city.country === "NO") pais = "(NORUEGA)"
            if (city.country === "OM") pais = "(OMAN)"
            if (city.country === "PK") pais = "(PAKISTAN)"
            if (city.country === "PW") pais = "(PALAOS)"
            if (city.country === "PS") pais = "(TERRITORIOS PALESTINOS)"
            if (city.country === "PA") pais = "(PANAMA)"
            if (city.country === "PG") pais = "(PAPUA NUEVA GUINEA)"
            if (city.country === "PY") pais = "(PARAGUAY)"
            if (city.country === "PE") pais = "(PERU)"
            if (city.country === "PH") pais = "(FILIPINAS)"
            if (city.country === "PN") pais = "(ISLAS PITCAIRN)"
            if (city.country === "PL") pais = "(POLONIA)"
            if (city.country === "PT") pais = "(PORTUGAL)"
            if (city.country === "PR") pais = "(PUERTO RICO)"
            if (city.country === "QA") pais = "(QATAR)"
            if (city.country === "RE") pais = "(REUNION)"
            if (city.country === "RO") pais = "(RUMANIA)"
            if (city.country === "RU") pais = "(RUSIA)"
            if (city.country === "RW") pais = "(RWANDA)"
            if (city.country === "BL") pais = "(SAN BARTOLOME)"
            if (city.country === "SH") pais = "(ISLA SANTA ELENA)"
            if (city.country === "KN") pais = "(SAN CRISTOBAL Y NIEVES)"
            if (city.country === "LC") pais = "(SANTA LUCIA)"
            if (city.country === "MF") pais = "(SAN MARTIN)"
            if (city.country === "PM") pais = "(SAN PEDRO Y MIQUELON)"
            if (city.country === "VC") pais = "(SAN VICENTE Y LAS GRANADINAS)"
            if (city.country === "WS") pais = "(SAMOA)"
            if (city.country === "SM") pais = "(SAN MARINO)"
            if (city.country === "ST") pais = "(SANTO TOMÉ Y PRÍNCIPE)"
            if (city.country === "SA") pais = "(ARABIA SAUDITA)"
            if (city.country === "SN") pais = "(SENEGAL)"
            if (city.country === "RS") pais = "(SERBIA)"
            if (city.country === "SC") pais = "(SEYCHELLES)"
            if (city.country === "SL") pais = "(SIERRA LEONA)"
            if (city.country === "SG") pais = "(SINGAPORE)"
            if (city.country === "SX") pais = "(SAN MARTIN (PAISES BAJOS))"
            if (city.country === "SK") pais = "(ESLOVAQUIA)"
            if (city.country === "SI") pais = "(ESLOVENIA)"
            if (city.country === "SB") pais = "(ISLAS SOLOMON)"
            if (city.country === "SO") pais = "(SOMALIA)"
            if (city.country === "ZA") pais = "(SUDAFRICA)"
            if (city.country === "GS") pais = "(ISLAS GEORGIAS DEL SUR Y SANDWICH DEL SUR)"
            if (city.country === "SS") pais = "(SUDAN DEL SUR)"
            if (city.country === "ES") pais = "(ESPAÑA)"
            if (city.country === "LK") pais = "(SRI LANKA)"
            if (city.country === "SD") pais = "(SUDAN)"
            if (city.country === "SR") pais = "(SURINAM)"
            if (city.country === "SJ") pais = "(SVALBARD Y JAN MAYEN)"
            if (city.country === "SZ") pais = "(SUAZILANDIA)"
            if (city.country === "SE") pais = "(SUECIA)"
            if (city.country === "CH") pais = "(SUIZA)"
            if (city.country === "SY") pais = "(SIRIA)"
            if (city.country === "TW") pais = "(TAIWAN)"
            if (city.country === "TJ") pais = "(TAYIKISTÁN)"
            if (city.country === "TZ") pais = "(TANZANIA)"
            if (city.country === "TH") pais = "(TAILANDIA)"
            if (city.country === "TL") pais = "(TIMOR ORIENTAL)"
            if (city.country === "TG") pais = "(TOGO)"
            if (city.country === "TK") pais = "(TOKELAU)"
            if (city.country === "TO") pais = "(TONGA)"
            if (city.country === "TT") pais = "(TRINIDAD AND TOBAGO)"
            if (city.country === "TN") pais = "(TUNEZ)"
            if (city.country === "TR") pais = "(TURQUIA)"
            if (city.country === "TM") pais = "(TURKMENISTAN)"
            if (city.country === "TC") pais = "(ISLAS TURCAS Y CAICOS)"
            if (city.country === "TV") pais = "(TUVALU)"
            if (city.country === "UG") pais = "(UGANDA)"
            if (city.country === "UA") pais = "(UCRANIA)"
            if (city.country === "AE") pais = "(EMIRATOS ÁRABES UNIDOS)"
            if (city.country === "GB") pais = "(REINO UNIDO)"
            if (city.country === "UM") pais = "(ISLAS ULTRAMARINAS MENORES DE LOS ESTADOS UNIDOS)"
            if (city.country === "US") pais = "(ESTADOS UNIDOS)"
            if (city.country === "UY") pais = "(URUGUAY)"
            if (city.country === "UZ") pais = "(UZBEKISTAN)"
            if (city.country === "VU") pais = "(VANUATU)"
            if (city.country === "VE") pais = "(VENEZUELA)"
            if (city.country === "VN") pais = "(VIETNAM)"
            if (city.country === "VG") pais = "(ISLAS VÍRGENES BRITÁNICAS)"
            if (city.country === "VI") pais = "(ISLAS VÍRGENES DE ESTADOS UNIDOS)"
            if (city.country === "WF") pais = "(WALLIS AND FUTUNA)"
            if (city.country === "EH") pais = "(SAHARA OCCIDENTAL)"
            if (city.country === "YE") pais = "(YEMEN)"
            if (city.country === "ZM") pais = "(ZAMBIA)"
            if (city.country === "ZW") pais = "(ZIMBABUE)"
              
    

            return (
                <div className="ciudad">
                        <div className="container">
                            <h2>{city.name}</h2>
                            <p className="card-country">{pais}</p>
                            <div className="info">
                                <div>Temperatura: {Math.round(city.temp * 10) / 10} ºC</div>
                                <div>Clima: {clima}</div>
                                <div>Viento: {Math.round(city.wind * 10) / 10} Km/h</div>
                                <div>Cantidad de nubes: {city.clouds} %</div>
                                
                            </div>
                        </div>
                </div>
            )
        } else {
            return (
                <div>
                    <h2>No hay ciudades..</h2>
                </div>
            )
        }

    } else {
    
        if (city) {

            if (city.country === "AF") pais = "(AFGHANISTAN)"
            if (city.country === "AX") pais = "(ALAND ISLANDS)"
            if (city.country === "AL") pais = "(ALBANIA)"
            if (city.country === "DZ") pais = "(ALGERIA)"
            if (city.country === "AS") pais = "(AMERICAN SAMOA)"
            if (city.country === "AD") pais = "(ANDORRA)"
            if (city.country === "AO") pais = "(ANGOLA)"
            if (city.country === "AI") pais = "(ANGUILLA)"
            if (city.country === "AQ") pais = "(ANTARCTICA)"
            if (city.country === "AG") pais = "(ANTIGUA AND BARBUDA)"
            if (city.country === "AR") pais = "(ARGENTINA)"
            if (city.country === "AM") pais = "(ARMENIA)"
            if (city.country === "AW") pais = "(ARUBA)"
            if (city.country === "AU") pais = "(AUSTRALIA)"
            if (city.country === "AT") pais = "(AUSTRIA)"
            if (city.country === "AZ") pais = "(AZERBAIJAN)"
            if (city.country === "BS") pais = "(BAHAMAS)"
            if (city.country === "BH") pais = "(BAHRAIN)"
            if (city.country === "BD") pais = "(BANGLADESH)"
            if (city.country === "BB") pais = "(BARBADOS)"
            if (city.country === "BY") pais = "(BELARUS)"
            if (city.country === "BE") pais = "(BELGIUM)"
            if (city.country === "BZ") pais = "(BELIZE)"
            if (city.country === "BJ") pais = "(BENIN)"
            if (city.country === "BM") pais = "(BERMUDA)"
            if (city.country === "BT") pais = "(BHUTAN)"
            if (city.country === "BO") pais = "(BOLIVIA)"
            if (city.country === "BQ") pais = "(BONAIRE, SINT EUSTATIUS AND SABA)"
            if (city.country === "BA") pais = "(BOSNIA AND HERZEGOVINA)"
            if (city.country === "BW") pais = "(BOTSWANA)"
            if (city.country === "BV") pais = "(BOUVET ISLAND)"
            if (city.country === "BR") pais = "(BRAZIL)"
            if (city.country === "IO") pais = "(BRITISH INDIAN OCEAN TERRITORY)"
            if (city.country === "BN") pais = "(BRUNEI DARUSSALAM)"
            if (city.country === "BG") pais = "(BULGARIA)"
            if (city.country === "BF") pais = "(BURKINA FASO)"
            if (city.country === "BI") pais = "(BURUNDI)"
            if (city.country === "KH") pais = "(CAMBODIA)"
            if (city.country === "CM") pais = "(CAMEROON)"
            if (city.country === "CA") pais = "(CANADA)"
            if (city.country === "CV") pais = "(CAPE VERDE)"
            if (city.country === "KY") pais = "(CAYMAN ISLANDS)"
            if (city.country === "CF") pais = "(CENTRAL AFRICAN REPUBLIC)"
            if (city.country === "TD") pais = "(CHAD)"
            if (city.country === "CL") pais = "(CHILE)"
            if (city.country === "CN") pais = "(CHINA)"
            if (city.country === "CX") pais = "(CHRISTMAS ISLAND)"
            if (city.country === "CC") pais = "(COCOS (KEELING) ISLANDS)"
            if (city.country === "CO") pais = "(COLOMBIA)"
            if (city.country === "KM") pais = "(COMOROS)"
            if (city.country === "CD") pais = "(THE DEMOCRATIC REPUBLIC OF THE CONGO)"
            if (city.country === "CG") pais = "(CONGO)"
            if (city.country === "CK") pais = "(COOK ISLANDS)"
            if (city.country === "CR") pais = "(COSTA RICA)"
            if (city.country === "CI") pais = "(CÔTE D'IVOIRE)"
            if (city.country === "HR") pais = "(CROATIA)"
            if (city.country === "CU") pais = "(CUBA)"
            if (city.country === "CW") pais = "(CURAÇAO)"
            if (city.country === "CY") pais = "(CYPRUS)"
            if (city.country === "CZ") pais = "(CZECH REPUBLIC)"
            if (city.country === "DK") pais = "(DENMARK)"
            if (city.country === "DJ") pais = "(DJIBOUTI)"
            if (city.country === "DM") pais = "(DOMINICA)"
            if (city.country === "DO") pais = "(DOMINICAN REPUBLIC)"
            if (city.country === "EC") pais = "(ECUADOR)"
            if (city.country === "EG") pais = "(EGYPT)"
            if (city.country === "SV") pais = "(EL SALVADOR)"
            if (city.country === "GQ") pais = "(EQUATORIAL GUINEA)"
            if (city.country === "ER") pais = "(ERITREA)"
            if (city.country === "EE") pais = "(ESTONIA)"
            if (city.country === "ET") pais = "(ETHIOPIA)"
            if (city.country === "FK") pais = "(FALKLAND ISLANDS)"
            if (city.country === "FO") pais = "(FAROE ISLANDS)"
            if (city.country === "FJ") pais = "(FIJI)"
            if (city.country === "FI") pais = "(FINLAND)"
            if (city.country === "FR") pais = "(FRANCE)"
            if (city.country === "GF") pais = "(FRENCH GUIANA)"
            if (city.country === "PF") pais = "(FRENCH POLYNESIA)"
            if (city.country === "TF") pais = "(FRENCH SOUTHERN TERRITORIES)"
            if (city.country === "GA") pais = "(GABON)"
            if (city.country === "GM") pais = "(GAMBIA)"
            if (city.country === "GE") pais = "(GEORGIA)"
            if (city.country === "DE") pais = "(GERMANY)"
            if (city.country === "GH") pais = "(GHANA)"
            if (city.country === "GI") pais = "(GIBRALTAR)"
            if (city.country === "GR") pais = "(GREECE)"
            if (city.country === "GL") pais = "(GREENLAND)"
            if (city.country === "GD") pais = "(GRENADA)"
            if (city.country === "GP") pais = "(GUADELOUPE)"
            if (city.country === "GU") pais = "(GUAM)"
            if (city.country === "GT") pais = "(GUATEMALA)"
            if (city.country === "GG") pais = "(GUERNSEY)"
            if (city.country === "GW") pais = "(GUINEA-BISSAU)"
            if (city.country === "GN") pais = "(GUINEA)"
            if (city.country === "GY") pais = "(GUYANA)"
            if (city.country === "HT") pais = "(HAITI)"
            if (city.country === "HM") pais = "(HEARD ISLAND AND MCDONALD ISLANDS)"
            if (city.country === "VA") pais = "(HOLY SEE (VATICAN CITY STATE))"
            if (city.country === "HN") pais = "(HONDURAS)"
            if (city.country === "HK") pais = "(HONG KONG)"
            if (city.country === "HU") pais = "(HUNGARY)"
            if (city.country === "IS") pais = "(ICELAND)"
            if (city.country === "IN") pais = "(INDIA)"
            if (city.country === "ID") pais = "(INDONESIA)"
            if (city.country === "IR") pais = "(ISLAMIC REPUBLIC OF IRAN)"
            if (city.country === "IQ") pais = "(IRAQ)"
            if (city.country === "IE") pais = "(IRELAND)"
            if (city.country === "IM") pais = "(ISLE OF MAN)"
            if (city.country === "IL") pais = "(ISRAEL)"
            if (city.country === "IT") pais = "(ITALY)"
            if (city.country === "JM") pais = "(JAMAICA)"
            if (city.country === "JP") pais = "(JAPAN)"
            if (city.country === "JE") pais = "(JERSEY)"
            if (city.country === "JO") pais = "(JORDAN)"
            if (city.country === "KZ") pais = "(KAZAKHSTAN)"
            if (city.country === "KE") pais = "(KENYA)"
            if (city.country === "KI") pais = "(KIRIBATI)"
            if (city.country === "KP") pais = "(DEMOCRATIC PEOPLE'S REPUBLIC OF KOREA)"
            if (city.country === "KR") pais = "(REPUBLIC OF KOREA)"
            if (city.country === "KW") pais = "(KUWAIT)"
            if (city.country === "KG") pais = "(KYRGYZSTAN)"
            if (city.country === "LA") pais = "(LAO PEOPLE'S DEMOCRATIC REPUBLIC)"
            if (city.country === "LV") pais = "(LATVIA)"
            if (city.country === "LB") pais = "(LEBANON)"
            if (city.country === "LS") pais = "(LESOTHO)"
            if (city.country === "LR") pais = "(LIBERIA)"
            if (city.country === "LY") pais = "(LIBYAN ARAB JAMAHIRIYA)"
            if (city.country === "LI") pais = "(LIECHTENSTEIN)"
            if (city.country === "LT") pais = "(LITHUANIA)"
            if (city.country === "LU") pais = "(LUXEMBOURG)"
            if (city.country === "MO") pais = "(MACAO)"
            if (city.country === "MK") pais = "(MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF)"
            if (city.country === "MG") pais = "(MADAGASCAR)"
            if (city.country === "MW") pais = "(MALAWI)"
            if (city.country === "MY") pais = "(MALAYSIA)"
            if (city.country === "MV") pais = "(MALDIVES)"
            if (city.country === "ML") pais = "(MALI)"
            if (city.country === "MT") pais = "(MALTA)"
            if (city.country === "MH") pais = "(MARSHALL ISLANDS)"
            if (city.country === "MQ") pais = "(MARTINIQUE)"
            if (city.country === "MR") pais = "(MAURITANIA)"
            if (city.country === "MU") pais = "(MAURITIUS)"
            if (city.country === "YT") pais = "(MAYOTTE)"
            if (city.country === "MX") pais = "(MEXICO)"
            if (city.country === "FM") pais = "(MICRONESIA, FEDERATED STATES OF)"
            if (city.country === "MD") pais = "(MOLDOVA, REPUBLIC OF)"
            if (city.country === "MC") pais = "(MONACO)"
            if (city.country === "MN") pais = "(MONGOLIA)"
            if (city.country === "ME") pais = "(MONTENEGRO)"
            if (city.country === "MS") pais = "(MONTSERRAT)"
            if (city.country === "MA") pais = "(MOROCCO)"
            if (city.country === "MZ") pais = "(MOZAMBIQUE)"
            if (city.country === "MM") pais = "(MYANMAR)"
            if (city.country === "NA") pais = "(NAMIBIA)"
            if (city.country === "NR") pais = "(NAURU)"
            if (city.country === "NP") pais = "(NEPAL)"
            if (city.country === "NL") pais = "(NETHERLANDS)"
            if (city.country === "NC") pais = "(NEW CALEDONIA)"
            if (city.country === "NZ") pais = "(NEW ZEALAND)"
            if (city.country === "NI") pais = "(NICARAGUA)"
            if (city.country === "NG") pais = "(NIGERIA)"
            if (city.country === "NE") pais = "(NIGER)"
            if (city.country === "NU") pais = "(NIUE)"
            if (city.country === "NF") pais = "(NORFOLK ISLAND)"
            if (city.country === "MP") pais = "(NORTHERN MARIANA ISLANDS)"
            if (city.country === "NO") pais = "(NORWAY)"
            if (city.country === "OM") pais = "(OMAN)"
            if (city.country === "PK") pais = "(PAKISTAN)"
            if (city.country === "PW") pais = "(PALAU)"
            if (city.country === "PS") pais = "(PALESTINIAN TERRITORY, OCCUPIED)"
            if (city.country === "PA") pais = "(PANAMA)"
            if (city.country === "PG") pais = "(PAPUA NEW GUINEA)"
            if (city.country === "PY") pais = "(PARAGUAY)"
            if (city.country === "PE") pais = "(PERU)"
            if (city.country === "PH") pais = "(PHILIPPINES)"
            if (city.country === "PN") pais = "(PITCAIRN)"
            if (city.country === "PL") pais = "(POLAND)"
            if (city.country === "PT") pais = "(PORTUGAL)"
            if (city.country === "PR") pais = "(PUERTO RICO)"
            if (city.country === "QA") pais = "(QATAR)"
            if (city.country === "RE") pais = "(RÉUNION)"
            if (city.country === "RO") pais = "(ROMANIA)"
            if (city.country === "RU") pais = "(RUSSIAN FEDERATION)"
            if (city.country === "RW") pais = "(RWANDA)"
            if (city.country === "BL") pais = "(SAINT BARTHÉLEMY)"
            if (city.country === "SH") pais = "(SAINT HELENA)"
            if (city.country === "KN") pais = "(SAINT KITTS AND NEVIS)"
            if (city.country === "LC") pais = "(SAINT LUCIA)"
            if (city.country === "MF") pais = "(SAINT MARTIN (FRENCH PART))"
            if (city.country === "PM") pais = "(SAINT PIERRE AND MIQUELON)"
            if (city.country === "VC") pais = "(SAINT VINCENT AND THE GRENADINES)"
            if (city.country === "WS") pais = "(SAMOA)"
            if (city.country === "SM") pais = "(SAN MARINO)"
            if (city.country === "ST") pais = "(SAO TOME AND PRINCIPE)"
            if (city.country === "SA") pais = "(SAUDI ARABIA)"
            if (city.country === "SN") pais = "(SENEGAL)"
            if (city.country === "RS") pais = "(SERBIA)"
            if (city.country === "SC") pais = "(SEYCHELLES)"
            if (city.country === "SL") pais = "(SIERRA LEONE)"
            if (city.country === "SG") pais = "(SINGAPORE)"
            if (city.country === "SX") pais = "(SINT MAARTEN (DUTCH PART))"
            if (city.country === "SK") pais = "(SLOVAKIA)"
            if (city.country === "SI") pais = "(SLOVENIA)"
            if (city.country === "SB") pais = "(SOLOMON ISLANDS)"
            if (city.country === "SO") pais = "(SOMALIA)"
            if (city.country === "ZA") pais = "(SOUTH AFRICA)"
            if (city.country === "GS") pais = "(SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS)"
            if (city.country === "SS") pais = "(SOUTH SUDAN)"
            if (city.country === "ES") pais = "(SPAIN)"
            if (city.country === "LK") pais = "(SRI LANKA)"
            if (city.country === "SD") pais = "(SUDAN)"
            if (city.country === "SR") pais = "(SURINAME)"
            if (city.country === "SJ") pais = "(SVALBARD AND JAN MAYEN)"
            if (city.country === "SZ") pais = "(SWAZILAND)"
            if (city.country === "SE") pais = "(SWEDEN)"
            if (city.country === "CH") pais = "(SWITZERLAND)"
            if (city.country === "SY") pais = "(SYRIAN ARAB REPUBLIC)"
            if (city.country === "TW") pais = "(PROVINCE OF CHINA TAIWAN)"
            if (city.country === "TJ") pais = "(TAJIKISTAN)"
            if (city.country === "TZ") pais = "(UNITED REPUBLIC OF TANZANIA)"
            if (city.country === "TH") pais = "(THAILAND)"
            if (city.country === "TL") pais = "(TIMOR-LESTE)"
            if (city.country === "TG") pais = "(TOGO)"
            if (city.country === "TK") pais = "(TOKELAU)"
            if (city.country === "TO") pais = "(TONGA)"
            if (city.country === "TT") pais = "(TRINIDAD AND TOBAGO)"
            if (city.country === "TN") pais = "(TUNISIA)"
            if (city.country === "TR") pais = "(TURKEY)"
            if (city.country === "TM") pais = "(TURKMENISTAN)"
            if (city.country === "TC") pais = "(TURKS AND CAICOS ISLANDS)"
            if (city.country === "TV") pais = "(TUVALU)"
            if (city.country === "UG") pais = "(UGANDA)"
            if (city.country === "UA") pais = "(UKRAINE)"
            if (city.country === "AE") pais = "(UNITED ARAB EMIRATES)"
            if (city.country === "GB") pais = "(UNITED KINGDOM)"
            if (city.country === "UM") pais = "(UNITED STATES MINOR OUTLYING ISLANDS)"
            if (city.country === "US") pais = "(UNITED STATES)"
            if (city.country === "UY") pais = "(URUGUAY)"
            if (city.country === "UZ") pais = "(UZBEKISTAN)"
            if (city.country === "VU") pais = "(VANUATU)"
            if (city.country === "VE") pais = "(VENEZUELA)"
            if (city.country === "VN") pais = "(VIETNAM)"
            if (city.country === "VG") pais = "(VIRGIN ISLANDS, BRITISH)"
            if (city.country === "VI") pais = "(VIRGIN ISLANDS, USA)"
            if (city.country === "WF") pais = "(WALLIS AND FUTUNA)"
            if (city.country === "EH") pais = "(WESTERN SAHARA)"
            if (city.country === "YE") pais = "(YEMEN)"
            if (city.country === "ZM") pais = "(ZAMBIA)"
            if (city.country === "ZW") pais = "(ZIMBABWE)"

            



            return (
                <div>
                    <div className="ciudad">
                            <div className="container">
                                <h2>{city.name}</h2>
                                <p className="card-country">{pais}</p>
                                <div className="info">
                                    <div>Temperature: {Math.round(((city.temp * (9/5)) + 32) * 10) / 10} ºF</div>
                                    <div>Weather: {city.weather}</div>
                                    <div>Wind: {Math.round((city.wind * 0.621371) * 10) / 10} MPH</div>
                                    <div>Clouds amount: {city.clouds} %</div>
                                   
                                </div>
                            </div>
                    </div>
                    
                </div>
            )
        } else {
            return (
                <div>
                    <h2>No cities..</h2>
                </div>
            )
        }

    }
    
    
}