name: Node.js CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.20.0]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
##    - name: Deploy
##      with:
##        token: ${{ github.token }}
##    - run: git config --global credential.https://github.com.username git
##    - git config --global credential.https://github.com.password <your-pat>
    - uses: de-vri-es/setup-git-credentials@v2
      with:
        credentials: ${{secrets.GIT_CREDENTIALS}}
    - run: git config --global user.email "juanpabloazambuyo@gmail.com"
    - run: git config --global user.name "Juan-Pablo-Azambuyo"
    - run: npm run deploy --if-present
