name: Auto Deploy
on:
  push:
    branches: [ "main" ]
env:
  CI: false
  REACT_APP_MAP: ${{ secrets.REACT_APP_MAP }}
  REACT_APP_WEATHER: ${{ secrets.REACT_APP_WEATHER }}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.20.0]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Copy README from origin root to GH-Pages public folder
      run: cp "./README.md" "./public/README.md"
    - run: npm ci
    - run: npm run build --if-present
    - run: git config --global user.email "juanpabloazambuyo@gmail.com"
    - run: git config --global user.name "Juan Pablo Azambuyo"
    - uses: actions/labeler@v4
      env:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - run: git remote set-url origin https://${{repo-token}}@github.com/PabloAza89/weather-app.git
    - run: npm run deploy --if-present